# Use the official Python image as a base image
# FROM python:3.11.9
FROM python:3.12.2

# Set the working directory inside the container
WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt
# Install dependencies
COPY . /app/


# Copy the rest of the application code to the working directory

# Run database migrations and collect static files
# RUN python manage.py migrate
# Expose the port that the Gunicorn app runs on
EXPOSE 8000

CMD ["daphne" "-b" "0.0.0.0" "-p" "8000" "task1.asgi.application"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
